name: Lint
run-name: ${{ github.actor }} is testing out Lint ðŸš€
on: [push]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Yarn
        run: yarn install

      - name: Usage Yarn Lint
        run: yarn lint

      - name: Usage Yarn Test
        run: yarn tests
    
      - name: Build the project
        run: yarn build

      - name: Install mkdocks - pip
        run: pip install mkdocs


